In [4]:
import pandas as pd
titanic_df=pd.read_csv(r"C:\Users\anupa\OneDrive\Desktop\Anupam\Python_SURE\exam\Titanic-Dataset.csv")

In [5]:
import numpy as np

In [4]:
titanic_df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Gender', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [5]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Gender       891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
titanic_np = titanic_df[['Age','Fare','Survived']].to_numpy()
print(type(titanic_np)) 
# using to_numpy() function we can directly convert Pandas Series to numpy

<class 'numpy.ndarray'>

In [7]:
print(titanic_df.shape)

(891, 12)

In [ ]:
titanic_df = titanic_df[['Age', 'Fare', 'Survived']].dropna()
print(titanic_df.shape)
print(titanic_df.head(10))
#Dropna drops values which has empty cell across these columns

(714, 3)
     Age     Fare  Survived
0   22.0   7.2500         0
1   38.0  71.2833         1
2   26.0   7.9250         1
3   35.0  53.1000         1
4   35.0   8.0500         0
6   54.0  51.8625         0
7    2.0  21.0750         0
8   27.0  11.1333         1
9   14.0  30.0708         1
10   4.0  16.7000         1

In [ ]:
titanic_df['Z_norm_age'] = (titanic_df['Age'] - titanic_df['Age'].mean()) / titanic_df['Age'].std()
titanic_df['Z_norm_fare'] = (titanic_df['Fare'] - titanic_df['Fare'].mean()) / titanic_df['Fare'].std()
print(titanic_df[['Age', 'Z_norm_age', 'Fare', 'Z_norm_fare']].head(10))
#Z=X-mean/Std deviation

     Age  Z_norm_age     Fare  Z_norm_fare
0   22.0   -0.530005   7.2500    -0.518614
1   38.0    0.571430  71.2833     0.691412
2   26.0   -0.254646   7.9250    -0.505859
3   35.0    0.364911  53.1000     0.347805
4   35.0    0.364911   8.0500    -0.503497
6   54.0    1.672866  51.8625     0.324421
7    2.0   -1.906799  21.0750    -0.257366
8   27.0   -0.185807  11.1333    -0.445232
9   14.0   -1.080723  30.0708    -0.087374
10   4.0   -1.769120  16.7000    -0.340039

In [ ]:
mean_values = titanic_df.groupby('Survived')[['Age', 'Fare']].mean()
print(mean_values)
#groupby can group same category of data

                Age       Fare
Survived
0         30.626179  22.965456
1         28.343690  51.843205

In [ ]:
fare_mean = titanic_df['Fare'].mean()
titanic_df['Fare_Class'] = np.where(titanic_df['Fare'] < fare_mean, 'Low', 'High')
print(titanic_df[['Fare', 'Fare_Class']].head(10))
#np.where can be used as (condition, value_if_true  ,value_if_false)

       Fare Fare_Class
0    7.2500        Low
1   71.2833       High
2    7.9250        Low
3   53.1000       High
4    8.0500        Low
6   51.8625       High
7   21.0750        Low
8   11.1333        Low
9   30.0708        Low
10  16.7000        Low

PANDAS

In [6]:
iris_df=pd.read_excel(r"C:\Users\anupa\OneDrive\Desktop\Anupam\Python_SURE\exam\iris.xlsx")

In [7]:
iris_df.columns

Index(['sepal.length', 'sepal.width', 'petal.length', 'petal.width',
       'variety'],
      dtype='object')

In [8]:
iris_df['petal_ratio']=iris_df['petal.length']/iris_df['petal.width']
iris_df.head(10)
#adding of new column which has length/width

   sepal.length  sepal.width  petal.length  petal.width variety  petal_ratio
0           5.1          3.5           1.4          0.2  Setosa     7.000000
1           4.9          3.0           1.4          0.2  Setosa     7.000000
2           4.7          3.2           1.3          0.2  Setosa     6.500000
3           4.6          3.1           1.5          0.2  Setosa     7.500000
4           5.0          3.6           1.4          0.2  Setosa     7.000000
5           5.4          3.9           1.7          0.4  Setosa     4.250000
6           4.6          3.4           1.4          0.3  Setosa     4.666667
7           5.0          3.4           1.5          0.2  Setosa     7.500000
8           4.4          2.9           1.4          0.2  Setosa     7.000000
9           4.9          3.1           1.5          0.1  Setosa    15.000000

In [9]:
iris_df['average_petal_ratio_per_species']=iris_df.groupby(by='variety')['petal_ratio'].transform('mean')
print(iris_df.head(10))
print(iris_df.tail(10))

   sepal.length  sepal.width  petal.length  petal.width variety  petal_ratio  \
0           5.1          3.5           1.4          0.2  Setosa     7.000000
1           4.9          3.0           1.4          0.2  Setosa     7.000000
2           4.7          3.2           1.3          0.2  Setosa     6.500000
3           4.6          3.1           1.5          0.2  Setosa     7.500000
4           5.0          3.6           1.4          0.2  Setosa     7.000000
5           5.4          3.9           1.7          0.4  Setosa     4.250000
6           4.6          3.4           1.4          0.3  Setosa     4.666667
7           5.0          3.4           1.5          0.2  Setosa     7.500000
8           4.4          2.9           1.4          0.2  Setosa     7.000000
9           4.9          3.1           1.5          0.1  Setosa    15.000000

   average_petal_ratio_per_species
0                            6.908
1                            6.908
2                            6.908
3                            6.908
4                            6.908
5                            6.908
6                            6.908
7                            6.908
8                            6.908
9                            6.908
     sepal.length  sepal.width  petal.length  petal.width    variety  \
140           6.7          3.1           5.6          2.4  Virginica
141           6.9          3.1           5.1          2.3  Virginica
142           5.8          2.7           5.1          1.9  Virginica
143           6.8          3.2           5.9          2.3  Virginica
144           6.7          3.3           5.7          2.5  Virginica
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

     petal_ratio  average_petal_ratio_per_species
140     2.333333                         2.780662
141     2.217391                         2.780662
142     2.684211                         2.780662
143     2.565217                         2.780662
144     2.280000                         2.780662
145     2.260870                         2.780662
146     2.631579                         2.780662
147     2.600000                         2.780662
148     2.347826                         2.780662
149     2.833333                         2.780662

In [11]:
print(iris_df.groupby(by='variety')['sepal.length'].std())
print(iris_df.groupby(by='variety')['sepal.length'].std().max())

variety
Setosa        0.352490
Versicolor    0.516171
Virginica     0.635880
Name: sepal.length, dtype: float64
0.635879593274432

In [18]:
print(iris_df['sepal.width'].mean())
iris_df[iris_df['sepal.width']>iris_df['sepal.width'].mean()]

3.0573333333333337

,sepal.length,sepal.width,petal.length,petal.width,variety,petal_ratio,average_petal_ratio_per_species
0,5.1,3.5,1.4,0.2,Setosa,7.000000,6.908000
2,4.7,3.2,1.3,0.2,Setosa,6.500000,6.908000
3,4.6,3.1,1.5,0.2,Setosa,7.500000,6.908000
4,5.0,3.6,1.4,0.2,Setosa,7.000000,6.908000
5,5.4,3.9,1.7,0.4,Setosa,4.250000,6.908000
...,...,...,...,...,...,...,...
140,6.7,3.1,5.6,2.4,Virginica,2.333333,2.780662
141,6.9,3.1,5.1,2.3,Virginica,2.217391,2.780662
143,6.8,3.2,5.9,2.3,Virginica,2.565217,2.780662
144,6.7,3.3,5.7,2.5,Virginica,2.280000,2.780662
148,6.2,3.4,5.4,2.3,Virginica,2.347826,2.780662

In [17]:
iris_petalbelow_2 = iris_df[iris_df['petal_ratio'] < 2]
iris_petalabove_2 = iris_df[iris_df['petal_ratio'] >= 2]
iris_petal_both = pd.concat([iris_petalbelow_2, iris_petalabove_2], axis=0)
print(iris_petal_both)

     sepal.length  sepal.width  petal.length  petal.width    variety  \
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

     petal_ratio  average_petal_ratio_per_species
0       7.000000                         6.908000
1       7.000000                         6.908000
2       6.500000                         6.908000
3       7.500000                         6.908000
4       7.000000                         6.908000
..           ...                              ...
145     2.260870                         2.780662
146     2.631579                         2.780662
147     2.600000                         2.780662
148     2.347826                         2.780662
149     2.833333                         2.780662

[150 rows x 7 columns]